export const GET_EVENTS = "GET_EVENTS";
export const CREATE_EVENT = "CREATE_EVENT";
export const CHANGE_EVENT = "CHANGE_EVENT";
export const REMOVE_EVENT = "REMOVE_EVENT";

export const CHANGE_DISPLAY_MODE = "CHANGE_DISPLAY_MODE";
export const CHANGE_MONTH = "CHANGE_MONTH";
export const CHANGE_YEAR = "CHANGE_YEAR";
export const CHANGE_START_WEEK = "CHANGE_START_WEEK";
export const CHANGE_SELECTED_DATE = "CHANGE_SELECTED_DATE";
